import type {ComponentPropsWithoutRef} from 'react'
import {type CssFunction} from '../../styled.d'

export enum IconType {
	activityCircle = 'activityCircle',
	aerobics = 'aerobics',
	alert = 'alert',
	alertFilled = 'alertFilled',
	arrowDown = 'arrowDown',
	arrowUp = 'arrowUp',
	bell = 'bell',
	bolt = 'bolt',
	boltCircle = 'boltCircle',
	boxing = 'boxing',
	cameraPlus = 'cameraPlus',
	check = 'check',
	checkCircle = 'checkCircle',
	chevronDown = 'chevronDown',
	chevronLeft = 'chevronLeft',
	chevronLeftCircle = 'chevronLeftCircle',
	chevronRight = 'chevronRight',
	chevronRightCircle = 'chevronRightCircle',
	chevronUp = 'chevronUp',
	circleExercise = 'circleExercise',
	clipboardCount = 'clipboardCount',
	comment = 'comment',
	contact = 'contact',
	contactFilled = 'contactFilled',
	contactList = 'contactList',
	contactPlus = 'contactPlus',
	cross = 'cross',
	crossCircle = 'crossCircle',
	cycling = 'cycling',
	dancing = 'dancing',
	delete = 'delete',
	drag = 'drag',
	download = 'download',
	dumbbell = 'dumbbell',
	dumbbellCircle = 'dumbbellCircle',
	duplicate = 'duplicate',
	edit = 'edit',
	ellipseMachine = 'ellipseMachine',
	envelope = 'envelope',
	exclamationMark = 'exclamationMark',
	exercise = 'exercise',
	eye = 'eye',
	faceFrown = 'faceFrown',
	faceMeh = 'faceMeh',
	faceSmile = 'faceSmile',
	female = 'female',
	file = 'file',
	filter = 'filter',
	flip = 'flip',
	gardening = 'gardening',
	goActive = 'goActive',
	goDeactivated = 'goDeactivated',
	goInvite = 'goInvite',
	goPending = 'goPending',
	golf = 'golf',
	grid = 'grid',
	history = 'history',
	home = 'home',
	homeFilled = 'homeFilled',
	horizontalEllipsis = 'horizontalEllipsis',
	iceSkating = 'iceSkating',
	indoorSpinning = 'indoorSpinning',
	info = 'info',
	infoCircle = 'infoCircle',
	kayak = 'kayak',
	library = 'library',
	libraryFilled = 'libraryFilled',
	link = 'link',
	lock = 'lock',
	male = 'male',
	menu = 'menu',
	menuFilled = 'menuFilled',
	messages = 'messages',
	messagesCircle = 'messagesCircle',
	minusCircle = 'minusCircle',
	nonbinary = 'nonbinary',
	paperPlaneCircle = 'paperPlaneCircle',
	phoneCircle = 'phoneCircle',
	pilates = 'pilates',
	plan = 'plan',
	placeholder = 'placeholder',
	plusCircle = 'plusCircle',
	plusStroke = 'plusStroke',
	printer = 'printer',
	profile = 'profile',
	program = 'program',
	programCircle = 'programCircle',
	progress = 'progress',
	qrCode = 'qrCode',
	questionMark = 'questionMark',
	racketGame = 'racketGame',
	related = 'related',
	riding = 'riding',
	rotate = 'rotate',
	rollerSkating = 'rollerSkating',
	roundedCross = 'roundedCross',
	roundedMinus = 'roundedMinus',
	roundedPlus = 'roundedPlus',
	rowing = 'rowing',
	rowingMachine = 'rowingMachine',
	running = 'running',
	search = 'search',
	send = 'send',
	settings = 'settings',
	share = 'share',
	stepMachine = 'stepMachine',
	today = 'today',
	trend = 'trend',
	trendDown = 'trendDown',
	trendUp = 'trendUp',
	skiing = 'skiing',
	skis = 'skis',
	skippingRope = 'skippingRope',
	smileCircle = 'smileCircle',
	snowboarding = 'snowboarding',
	star = 'star',
	starFilled = 'starFilled',
	strengthTraining = 'strengthTraining',
	swimming = 'swimming',
	table = 'table',
	tag = 'tag',
	teamSport = 'teamSport',
	time = 'time',
	timeCircle = 'timeCircle',
	verticalEllipsis = 'verticalEllipsis',
	video = 'video',
	walk = 'walk',
	walkingOnStairs = 'walkingOnStairs',
	yoga = 'yoga',
}

export enum IconSize {
	small = 7,
	medium = 9,
	large = 11,
	xlarge = 16,
	xxlarge = 20,
}

export type IconProperties = ComponentPropsWithoutRef<'svg'>

export type IconComponentProperties = IconProperties & {
	title?: string
	size?: number
	icon: IconType
	inputCss?: CssFunction
}
